export interface IHomeVideo {
    _id: string;
    videoUrl: string;
    title: string;
    description: string;
}

export interface IHomeVideoSection {
    _id: string;
    id: string; // This is the custom ID generated by generateID
    title: string;
    description: string;
    videos: IHomeVideo[];
    ctaButtonLabel: string;
    ctaButtonLink: string;
    isDeleted: boolean;
    createdAt?: string;
    updatedAt?: string;
}
